apiVersion: v1
kind: Service
metadata:
  name: reactcli-service
  annotations: 
    cloud.google.com/backend-config: '{"default": "reactcli-backend-config"}'
spec:
  type: NodePort
  selector:
    app: reactcli-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000